from pyvis.network import Network
import pprint
g = {'ASANA': [],
 'ASCEND at the Aspen Institute': [],
 'Akamai': [],
 'Alliance of Information and Referral Systems': [],
 'American Foundation for AIDS Research (amfAR)': [],
 'American Online Giving Foundation, Inc.': [],
 'American Type Culture Collection': [],
 'America’s Promise Alliance': [],
 'AmerisourceBergen Foundation': [],
 'Amgen Inc.': [],
 'Amgen USA': [],
 'Annie E. Casey Foundation': [],
 'Arizona Department of Health Services': [],
 'Attendance Works': [],
 'Auburn Graphics': [],
 'Barr Foundation': [],
 'Benevity': [],
 'Bethesda Lodge #301.O.O.F.': [],
 'Bill & Melinda Gates Foundation': [],
 'Bloomberg Philanthropies': [],
 'Blue Cross Blue Shield of MA': [],
 'Booz Allen Hamilton Inc.': [],
 'CDC Foundation': ['American Foundation for AIDS Research (amfAR)',
                    'American Online Giving Foundation, Inc.',
                    'American Type Culture Collection',
                    'AmerisourceBergen Foundation',
                    'Amgen Inc.',
                    'Amgen USA',
                    'Arizona Department of Health Services',
                    'Benevity',
                    'Bill & Melinda Gates Foundation',
                    'Bloomberg Philanthropies',
                    'Booz Allen Hamilton Inc.',
                    'California Department of Public Health',
                    'Centers for Disease Control and Prevention',
                    'The Chambers Family Foundation',
                    'Chicago Department of Public Health',
                    'City of Chicago',
                    'Communities Foundation of Texas',
                    'Crabby Beach Foundation',
                    'Dalio Philanthropies',
                    'Davycas International',
                    'Emergent BioSolutions Inc.',
                    'Emory University',
                    'ExxonMobil Foundation, Inc.',
                    'FHI 360',
                    'Fidelity Investments',
                    'The Fire Protection Research Foundation',
                    'Gavi Alliance',
                    'Google LLC',
                    "Hawai'i State Department of Health",
                    'Health Research, Inc.',
                    'Health Resources and Services Administration',
                    'The Howell Fund',
                    'Imperial College London',
                    'The James F. and Sarah T. Fries Foundation',
                    'The John D. and Catherine T. MacArthur Foundation',
                    'Kaiser Permanente',
                    'Kaiser Permanente National Community Benefit Fund',
                    'Merck Sharp & Dohme Corp.',
                    'Meta',
                    'Michigan Department of Health and Human Services',
                    'Microsoft Rewards API',
                    'Navajo Department of Health',
                    'Navajo Nation',
                    'Network for Good',
                    'Nevada Department of Health and Human Services, Division '
                    'of Public and Behavioral Health',
                    'New Mexico Department of Health',
                    'NFL Foundation',
                    'North Carolina Department of Health and Human Services',
                    'North Dakota Department of Health',
                    'Oak Crest Institute of Science',
                    'Oak Foundation',
                    'PayPal Giving Fund',
                    'PayPal, Inc.',
                    'Pinterest',
                    'Prologis',
                    'Public Health Foundation',
                    'Robert Wood Johnson Foundation',
                    'The Rotary Foundation',
                    'Rotary International',
                    'Schmidt Futures',
                    'Schwab Charitable Fund',
                    'South Dakota Department of Health',
                    'Truist',
                    'Truist Charitable Fund',
                    'The UK Online Giving Foundation',
                    'United Health Foundation',
                    'United States Department of Health and Human Services',
                    'University of California, Riverside',
                    'University of North Carolina at Chapel Hill',
                    'Vanguard Charitable',
                    'Vital Strategies',
                    'Wallace Genetic Foundation',
                    'Washington State Department of Health',
                    'The Wilson Family Foundation',
                    'The Winston-Salem Foundation',
                    'World Health Organization'],
 'California Department of Public Health': [],
 'Camosse Foundation': [],
 'Campaign for Grade Level Reading': [],
 'Carroll Charitable Foundation': [],
 'Carter’s': [],
 'Catholic Charities': [],
 'Centers for Disease Control and Prevention': [],
 'Chicago Department of Public Health': [],
 'Children’s Place': [],
 'City of Chicago': [],
 'City of Worcester Department of Youth Opportunities': [],
 'Clear Path': [],
 'Coalition for Community Schools': [],
 'Commonwealth Corporation': [],
 'Communities Foundation of Texas': [],
 'Community Economic Development Assistance Corporation': [],
 'Community Foundation of North Central Massachusetts': [],
 'Community Foundation of Western MA': [],
 'Cooper’s Hilltop Farm': [],
 'Country Bank': [],
 'County Health Rankings and Roadmaps': [],
 'Crabby Beach Foundation': [],
 'Curaleaf Massachusetts': [],
 'Dalio Philanthropies': [],
 'Davycas International': [],
 'Delivering Good': [],
 'ES Veterans Association': [],
 'Eastern Bank Foundation': [],
 'Emergent BioSolutions Inc.': [],
 'Emory University': [],
 'Esler Family Foundation': [],
 'Everbeez Graphics': [],
 'Executive Office of Health and Human Services': [],
 'Executive Office of Public Safety': [],
 'ExxonMobil Foundation, Inc.': [],
 'FHI 360': [],
 'FINRA Investor Education Foundation': [],
 'Fallon Health': [],
 'Favulli Electric': [],
 'Felicia Fund, Inc': [],
 'Fidelity Investments': [],
 'Forum for Youth Investment': [],
 'Gavi Alliance': [],
 'Google LLC': [],
 'Greater Worcester Community Foundation': [],
 'Grotonwood Conference Center': [],
 'Handel and Haydn Society': [],
 'Harvard Pilgrim Health Care': [],
 "Hawai'i State Department of Health": [],
 'Health Foundation of Central Massachusetts': [],
 'Health Research, Inc.': [],
 'Health Resources and Services Administration': [],
 'Healthy Weight Commitment Foundation': [],
 'Hermann Foundation': [],
 'Highland Street Foundation': [],
 'Historic New England': [],
 'Imperial College London': [],
 'In Memory of Spc. Bryan Torres': [],
 'Joy of Music Program': [],
 'K9 Mission': [],
 'Kaiser Permanente': [],
 'Kaiser Permanente National Community Benefit Fund': [],
 'Karen Amlaw Music': [],
 'Leadership 18': [],
 'Legendary Legacies': ['Worcester Community Action Council',
                        'Worcester County District Attorney',
                        'The Journey Community Church',
                        'Liberty Churches',
                        'Greater Worcester Community Foundation',
                        'Living Word Church of Worcester',
                        'Massachusetts Department of Youth Services',
                        'The Lenny Zakim Fund',
                        'Worcester Family Resource Center at YOU Inc.',
                        'Worcester Police Department',
                        "Worcester County Sheriff's Office",
                        "Rocco's Doughnuts",
                        'National Gang Crime Research Center',
                        'United Way of Central MA',
                        'Liberty Construction',
                        'Blue Cross Blue Shield of MA',
                        'Reliant Foundation',
                        'The Abbey of the Way',
                        'Everbeez Graphics',
                        'Barr Foundation',
                        'Catholic Charities',
                        'City of Worcester Department of Youth Opportunities',
                        'Worcester WooSox',
                        'Executive Office of Public Safety',
                        'Executive Office of Health and Human Services',
                        'Commonwealth Corporation',
                        'Promoting Good'],
 'Liberty Churches': [],
 'Liberty Construction': [],
 'Lilac Hedge Farm': [],
 'Living Word Church of Worcester': [],
 'Local Initiatives Support Corporation (LISC)': [],
 'Lt. Scott F. Milley Fund': [],
 'MDC': [],
 'Maine Drinking Water Program': [],
 'Mass Humanities': [],
 'Massachusetts Cultural Council': [],
 'Massachusetts Department of Youth Services': [],
 'Massachusetts Housing Partnership': [],
 'Massachusetts Rehabilitation Commission': [],
 'Mechanics Hall': [],
 'Merck Sharp & Dohme Corp.': [],
 'Meta': [],
 'Michigan Department of Health and Human Services': [],
 'Microsoft Rewards API': [],
 'Music Worcester': [],
 'NFL Foundation': [],
 'National Community Reinvestment Coalition': [],
 'National Disability Institute': [],
 'National Endowment for the Humanities': [],
 'National Gang Crime Research Center': [],
 'National Human Services Assembly': [],
 'National Summer Learning Association': [],
 'National Trust for Historic Preservation': [],
 'National Youth Leadership Council': [],
 'NationalGrid': [],
 'Navajo Department of Health': [],
 'Navajo Nation': [],
 'Network for Good': [],
 'Nevada Department of Health and Human Services, Division of Public and Behavioral Health': [],
 'New Mexico Department of Health': [],
 'NewVue Communities': [],
 'No Kid Hungry - Share Our Strength': [],
 'North Carolina Department of Health and Human Services': [],
 'North Dakota Department of Health': [],
 'Northeast Promotion & Apparel': [],
 'Oak Crest Institute of Science': [],
 'Oak Foundation': [],
 'Oceanwood Conference Center': [],
 'Officer Ronald Tarantino Jr. Charitable Fund': [],
 'One Each Technologies': [],
 'Opportunity Nation': [],
 'Pakachoag Music School': [],
 'PayPal Giving Fund': [],
 'PayPal, Inc.': [],
 'Pinterest': [],
 'Preservation Worcester': ['Carroll Charitable Foundation',
                            'Esler Family Foundation',
                            'Favulli Electric',
                            'Felicia Fund, Inc',
                            'The Fletcher Foundation',
                            'Hermann Foundation',
                            'Health Foundation of Central Massachusetts',
                            'Historic New England',
                            'Mass Humanities',
                            'Massachusetts Cultural Council',
                            'National Endowment for the Humanities',
                            'National Trust for Historic Preservation',
                            'Richard A. Heald Fund',
                            'The Schwartz Charitable Foundation',
                            'Sharfmans Jewelers',
                            'Shwachman Family Fund',
                            'Sira Naturals',
                            'Stoddard Charitable Trust',
                            'Tonna Charitable Trust',
                            'Worcester Arts Council',
                            'Worcester Educational Development Foundation, '
                            'Inc.'],
 'Prevention Institute': [],
 'Project New Hope': ['Camosse Foundation',
                      'Community Foundation of Western MA',
                      'Highland Street Foundation',
                      'Warren Fletcher',
                      'Curaleaf Massachusetts',
                      'Bethesda Lodge #301.O.O.F.',
                      'Akamai',
                      'Eastern Bank Foundation',
                      'Officer Ronald Tarantino Jr. Charitable Fund',
                      'Lt. Scott F. Milley Fund',
                      'In Memory of Spc. Bryan Torres',
                      'K9 Mission',
                      'Country Bank',
                      'Auburn Graphics',
                      'ES Veterans Association',
                      'Delivering Good',
                      'Grotonwood Conference Center',
                      'Harvard Pilgrim Health Care',
                      'NationalGrid',
                      'Northeast Promotion & Apparel',
                      'Oceanwood Conference Center',
                      'United Way of Central Mass',
                      'Wagner Motorsports',
                      'Clear Path',
                      'Lilac Hedge Farm',
                      'Cooper’s Hilltop Farm',
                      'Greater Worcester Community Foundation',
                      'Worcester Bravehearts',
                      'Saint-Gobain',
                      'Carter’s',
                      'Fallon Health',
                      'Children’s Place'],
 'Prologis': [],
 'Promoting Good': [],
 'Public Health Foundation': [],
 'RCAP Solutions': ['Rural Community Assistance Partnership',
                    'Regional Housing Network of Massachusetts',
                    'The Cadmus Group',
                    'The Chris Long Foundation',
                    'Community Economic Development Assistance Corporation',
                    'Community Foundation of North Central Massachusetts',
                    'The Health Foundation of Central Massachusetts',
                    'Maine Drinking Water Program',
                    'Massachusetts Housing Partnership',
                    'Massachusetts Rehabilitation Commission',
                    'The Milken Institute',
                    'National Community Reinvestment Coalition',
                    'NewVue Communities',
                    'Rhode Island Department of Health',
                    'Rhode Island Infrastructure Bank',
                    'Rural Community Development',
                    'Siegel Family Endowment',
                    'Susquehanna River Basin Commission',
                    'Wells Fargo Foundation',
                    'Worcester Community Action Coalition'],
 'Regional Housing Network of Massachusetts': [],
 'Reliant Foundation': [],
 'Reliant Medical Group': [],
 'Rhode Island Department of Health': [],
 'Rhode Island Infrastructure Bank': [],
 'Richard A. Heald Fund': [],
 'Robert Wood Johnson Foundation': [],
 "Rocco's Doughnuts": [],
 'Rotary International': [],
 'Rural Community Assistance Partnership': [],
 'Rural Community Development': [],
 'Saint-Gobain': [],
 'Schmidt Futures': [],
 'Schwab Charitable Fund': [],
 'Sharfmans Jewelers': [],
 'Shwachman Family Fund': [],
 'Siegel Family Endowment': [],
 'Sira Naturals': [],
 'South Dakota Department of Health': [],
 'Stoddard Charitable Trust': [],
 'Susquehanna River Basin Commission': [],
 'The Abbey of the Way': [],
 'The Cadmus Group': [],
 'The Chambers Family Foundation': [],
 'The Chris Long Foundation': [],
 'The Fire Protection Research Foundation': [],
 'The Fletcher Foundation': [],
 'The Hanover Theatre': [],
 'The Health Foundation of Central Massachusetts': [],
 'The Howell Fund': [],
 'The James F. and Sarah T. Fries Foundation': [],
 'The John D. and Catherine T. MacArthur Foundation': [],
 'The Journey Community Church': [],
 'The Lenny Zakim Fund': [],
 'The Milken Institute': [],
 'The Rotary Foundation': [],
 'The Schwartz Charitable Foundation': [],
 'The UK Online Giving Foundation': [],
 'The Wilson Family Foundation': [],
 'The Winston-Salem Foundation': [],
 'Tonna Charitable Trust': [],
 'Truist': [],
 'Truist Charitable Fund': [],
 'Trust for America’s Health - Advocacy for Prevention and Public Health': [],
 'United Health Foundation': [],
 'United States Department of Health and Human Services': [],
 'United Way': ['United Way Worldwide',
                'CDC Foundation',
                'National Youth Leadership Council',
                'Trust for America’s Health - Advocacy for Prevention and '
                'Public Health',
                'Opportunity Nation',
                'National Human Services Assembly',
                'Leadership 18',
                'Forum for Youth Investment',
                'Coalition for Community Schools',
                'Alliance of Information and Referral Systems',
                'National Disability Institute',
                'MDC',
                'Local Initiatives Support Corporation (LISC)',
                'FINRA Investor Education Foundation',
                'Annie E. Casey Foundation',
                'No Kid Hungry - Share Our Strength',
                'Prevention Institute',
                'Healthy Weight Commitment Foundation',
                'County Health Rankings and Roadmaps',
                'One Each Technologies',
                'ASANA',
                'National Summer Learning Association',
                'Campaign for Grade Level Reading',
                'Attendance Works',
                'ASCEND at the Aspen Institute',
                'America’s Promise Alliance'],
 'United Way Worldwide': [],
 'United Way of Central MA': [],
 'United Way of Central Mass': [],
 'University of California, Riverside': [],
 'University of North Carolina at Chapel Hill': [],
 'Vanguard Charitable': [],
 'Vital Strategies': [],
 'Wagner Motorsports': [],
 'Wallace Genetic Foundation': [],
 'Warren Fletcher': [],
 'Washington State Department of Health': [],
 'Wells Fargo Foundation': [],
 'Worcester Arts Council': [],
 'Worcester Bravehearts': [],
 'Worcester Chamber Music Society': ['Karen Amlaw Music',
                                     'Handel and Haydn Society',
                                     'Joy of Music Program',
                                     'The Hanover Theatre',
                                     'Mechanics Hall',
                                     'Music Worcester',
                                     'Pakachoag Music School',
                                     'Reliant Medical Group',
                                     'Worcester Music Academy',
                                     'Worcester Youth Orchestra'],
 'Worcester Community Action Coalition': [],
 'Worcester Community Action Council': [],
 'Worcester County District Attorney': [],
 "Worcester County Sheriff's Office": [],
 'Worcester Educational Development Foundation, Inc.': [],
 'Worcester Family Resource Center at YOU Inc.': [],
 'Worcester Music Academy': [],
 'Worcester Police Department': [],
 'Worcester WooSox': [],
 'Worcester Youth Orchestra': [],
 'World Health Organization': []}



# Create a Pyvis Network instance
net = Network(directed=True)

# Add nodes to the network
for node in g.keys():
    net.add_node(node)

# Add edges to the network
for node, neighbors in g.items():
    for neighbor in neighbors:
        net.add_edge(node, neighbor)

# Save the visualization as an HTML file
net.show("your_graph.html")
